# Generated by Django 3.0.8 on 2021-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopify_api',
            name='company',
            field=models.CharField(blank=True, default=0, max_length=225, null=True),
        ),
    ]
