# Generated by Django 3.0.8 on 2021-03-02 21:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('notification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=0, max_length=50)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runOrderDay', models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thrusday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=2, null=True)),
                ('runOrderTime', models.TimeField(default=datetime.time(0, 0))),
                ('emailSent', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=225, unique=True)),
                ('barCode', models.CharField(default=0, max_length=10)),
                ('stockAmount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('reOrderAmount', models.IntegerField(default=0, null=True)),
                ('orderCode', models.CharField(default=0, max_length=10, null=True)),
                ('orderTrigger', models.IntegerField(blank=True, default=0, null=True)),
                ('orderTriggerByUser', models.CharField(default=0, max_length=225, null=True)),
                ('itemBookedInByUser', models.CharField(default=0, max_length=225, null=True)),
                ('lastOrdered', models.DateTimeField(blank=True, default=None, null=True)),
                ('onOrder', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=225, null=True, unique=True)),
                ('email', models.CharField(blank=True, default=0, max_length=225, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item_status',
            name='item_name',
        ),
        migrations.DeleteModel(
            name='supplier_details',
        ),
        migrations.DeleteModel(
            name='item_status',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.AddField(
            model_name='stockitems',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Suppliers'),
        ),
    ]
