# Generated by Django 3.0.8 on 2021-03-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_notifications_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='company',
            field=models.CharField(default=0, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='name',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
