# Generated by Django 3.0.8 on 2021-03-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210303_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitems',
            name='company',
        ),
    ]
