# Generated by Django 3.0.8 on 2021-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_stockitems_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='company',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
