# Generated by Django 3.0.8 on 2021-03-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockitems_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
    ]
