# Generated by Django 3.0.8 on 2021-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_suppliers_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('stockName', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
