# Generated by Django 3.0.8 on 2021-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='company',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
