# Generated by Django 3.0.8 on 2021-03-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_orderrequest_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
