# Generated by Django 3.0.8 on 2021-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_orderrequest_dateordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='reason',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
