# Generated by Django 3.0.8 on 2021-03-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_email_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='barCode',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='orderCode',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
