# Generated by Django 3.0.8 on 2021-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20210305_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='onOrder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
