# Generated by Django 3.0.8 on 2021-03-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_stockitems_consignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='consignmentProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=5000)),
            ],
        ),
    ]
