# Generated by Django 3.0.8 on 2021-03-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_consignmentprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='reserved',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
