# Generated by Django 3.0.8 on 2021-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_stockitems_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='billOfMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=225)),
                ('BOMname', models.CharField(max_length=225)),
                ('projectName', models.CharField(max_length=225)),
            ],
        ),
    ]
