# Generated by Django 3.0.8 on 2021-03-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_billofmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='bomStock',
            field=models.CharField(default=0, max_length=50000),
            preserve_default=False,
        ),
    ]
