# Generated by Django 3.0.8 on 2021-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_billofmaterials_bomstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='status',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
