# Generated by Django 3.0.8 on 2021-03-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_dupepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=225)),
                ('BOMProject', models.CharField(max_length=225)),
                ('BOMName', models.CharField(max_length=225)),
            ],
        ),
    ]
