# Generated by Django 3.0.8 on 2021-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_bomprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomprojects',
            name='uniqueBOMNumber',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
