# Generated by Django 3.0.8 on 2021-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_bomprojects_uniquebomnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
            ],
        ),
    ]
