# Generated by Django 3.0.8 on 2021-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=225)),
            ],
        ),
    ]
