# Generated by Django 3.0.8 on 2021-03-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_orderrequest_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='orderValue',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
