# Generated by Django 3.0.8 on 2021-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_orderrequest_ordervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
