# Generated by Django 3.0.8 on 2021-03-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_orderrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='company',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
