# Generated by Django 3.0.8 on 2021-03-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_notifications_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='storeGroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyGroupList', models.CharField(max_length=225)),
                ('companyGroupName', models.CharField(max_length=225)),
            ],
        ),
    ]
