# Generated by Django 3.0.8 on 2021-03-15 10:17

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_remove_storegrouplist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='uniqueStockNumber',
            field=models.CharField(default=0, max_length=22500),
        ),
    ]
