# Generated by Django 3.0.8 on 2021-03-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_stockitems_uniquestocknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='uniqueStockNumber',
            field=models.CharField(default=0, max_length=22500),
        ),
    ]
