# Generated by Django 3.0.8 on 2021-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_orderrequest_uniquestocknumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='bomUniqueID',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
