# Generated by Django 3.0.8 on 2021-03-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_billofmaterials_bomuniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='bomUniqueID',
        ),
    ]
