# Generated by Django 3.0.8 on 2021-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_remove_billofmaterials_bomuniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomprojects',
            old_name='uniqueBOMNumber',
            new_name='uniqueBOMNameNumber',
        ),
        migrations.AddField(
            model_name='bomprojects',
            name='uniqueBOMProjectNumber',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
