# Generated by Django 3.0.8 on 2021-03-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_auto_20210319_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Suppliers'),
        ),
    ]
