# Generated by Django 3.0.8 on 2021-03-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_auto_20210319_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='shopify_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
