# Generated by Django 3.0.8 on 2021-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0050_stockitems_shopify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopifyInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('PID', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=225)),
                ('SKU', models.CharField(max_length=225)),
                ('bardocde', models.CharField(max_length=225)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('old_inventory_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
