# Generated by Django 3.0.8 on 2021-03-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_shopifyinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyinventory',
            name='stock_io_unique_number',
            field=models.IntegerField(default=0),
        ),
    ]
