# Generated by Django 3.0.8 on 2021-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0053_auto_20210331_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='barCode',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='uniqueStockNumber',
            field=models.CharField(default=0, max_length=22500, null=True),
        ),
    ]
