# Generated by Django 3.0.8 on 2021-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0054_auto_20210401_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyinventory',
            name='inventory_id',
            field=models.IntegerField(default=0),
        ),
    ]
