# Generated by Django 3.0.8 on 2021-04-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0055_shopifyinventory_inventory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyinventory',
            name='SID',
        ),
        migrations.AddField(
            model_name='shopifyinventory',
            name='location_item_id',
            field=models.IntegerField(default=0),
        ),
    ]
