# Generated by Django 3.0.8 on 2021-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0056_auto_20210406_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifyinventory',
            old_name='inventory_id',
            new_name='inventory_item_id',
        ),
        migrations.RenameField(
            model_name='shopifyinventory',
            old_name='location_item_id',
            new_name='location_id',
        ),
        migrations.AlterField(
            model_name='shopifyinventory',
            name='PID',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventory',
            name='SKU',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventory',
            name='bardocde',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventory',
            name='price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventory',
            name='stock_io_unique_number',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventory',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
