# Generated by Django 3.0.8 on 2021-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0057_auto_20210406_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyinventory',
            name='shopifyID',
            field=models.IntegerField(default=0),
        ),
    ]
