# Generated by Django 3.0.8 on 2021-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0058_shopifyinventory_shopifyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyinventory',
            name='variant_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
