# Generated by Django 3.0.8 on 2021-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0059_shopifyinventory_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_format',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
