# Generated by Django 3.0.8 on 2021-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_profile_email_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_format',
        ),
        migrations.AddField(
            model_name='company_email',
            name='email_format',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
