# Generated by Django 3.0.8 on 2021-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0062_auto_20210408_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_email_preference',
            name='company',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
