# Generated by Django 3.0.8 on 2021-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0065_auto_20210408_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user_id',
            field=models.CharField(max_length=225),
        ),
    ]
