# Generated by Django 3.0.8 on 2021-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0066_auto_20210414_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='allow_reorder',
            field=models.BooleanField(default=1),
        ),
    ]
