insert into "public"."stock_suppliers" ("id", "email", "name", "company")
values  (5, '0', 'DIRECT', 'Visualization'),
        (6, '0', 'CPC', 'Visualization'),
        (7, '0', 'EXTRON', 'Visualization'),
        (8, '0', 'LYRECO', 'Visualization'),
        (9, '0', 'EBAY', 'Visualization'),
        (10, '0', 'PENN', 'Visualization'),
        (11, '0', 'VDC', 'Visualization'),
        (12, '0', 'NETSHOP', 'Visualization'),
        (13, '0', 'LABELZONE', 'Visualization'),
        (14, '0', 'GASDEALS', 'Visualization'),
        (15, '0', 'bpfonline.co.uk', 'Visualization'),
        (16, '0', 'RS', 'Visualization'),
        (17, '0', 'WOODWAY', 'Visualization'),
        (18, '0', 'LABLEZONE', 'Visualization'),
        (19, '0', 'ABC COMPONETS LIMITED', 'Visualization'),
        (20, '0', 'RGB', 'Visualization'),
        (21, '0', 'ALLTRADE', 'Visualization'),
        (22, '0', 'KRAMER', 'Visualization'),
        (23, '0', 'NEUTRIK', 'Visualization'),
        (24, '0', 'AAV', 'Visualization'),
        (25, '0', 'KENABLE', 'Visualization'),
        (26, '0', 'COSTCO', 'Visualization'),
        (27, '0', 'ABC', 'Visualization'),
        (28, '0', 'PAPERSTONE', 'Visualization'),
        (29, '0', 'CONNECT CO', 'Visualization'),
        (30, '0', 'QUAD', 'Visualization'),
        (31, '0', 'TARGET', 'Visualization'),
        (32, '0', 'AMAZON', 'Visualization'),
        (33, '0', 'CRESTRON', 'Visualization'),
        (34, '0', 'ARGOSY', 'Visualization'),
        (35, '0', 'STORM TRADING', 'Visualization'),
        (36, '0', 'SCOLMORE', 'Visualization'),
        (37, '0', 'MAZER', 'Visualization');